package src.enums;

public enum Cursos {

  LOGICA_DE_PROGRAMACAO,
  JAVA,
  BANCO_DE_DADOS;

//TODO: ADICIONAR MAIS MATÉRIAS DE CURSO AQUI DENTRO DO ENUM E CONSEGUIR ATRIBUIR MAIS DE UMA MATÉRIA PARA A HABLIDADE DO ALUNO -> Gui
}
